---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
nfpms:
  - id: ansible-dev
    package_name: ansible-dev
    homepage: https://github.com/dcjulian29/ansible-dev/
    maintainer: Julian Easterling <julian@julianscorner.com>
    license: Apache 2.0
    description: |-
      ansible-dev integrates with Vagrant to enable users to define, develop, and test Ansible
      playbooks, roles, and modules. It allows users to define and manage infrastructure resources and
      uses the providers automation engine to provision and run plays.

      By utilizing Ansible's playbooks, roles, and modules, developers can automate the deployment of
      software applications across multiple hosting providers, reducing the time and effort required to
      manage complex infrastructure environments. These playbooks, roles, and modules enable developers to
      create, manage, and provision infrastructure resources like virtual machines, load balancers, and
      databases.
    formats:
      - rpm
      - deb
    bindir: /usr/local/bin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
