---
name: Continuous Integration
on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/ansible-dev

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ env.GOPATH }}/ansible-dev

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - run: |
          go build -v ./...
          go test -v ./...
