---
name: Continuous Integration
on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - run: |
          go build -v ./...
          go test -v ./...
        env:
          GOPATH: /home/runner/work/ansible-dev/ansible-dev
