---
name: Continuous Integration
on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/ansible-dev

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ env.GOPATH }}/ansible-dev

      - uses: actions/setup-go@v4
        with:
          cache-dependency-path: ${{ env.GOPATH }}/ansible-dev/go.sum
          go-version-file: ${{ env.GOPATH }}/ansible-dev/go.sum/go.mod

      - run: go version

      - run: go build -v ./...

      - run: go test -v ./...
