---
name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/ansible-dev

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ${{ env.GOPATH }}/ansible-dev

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          cache-dependency-path: ${{ env.GOPATH }}/ansible-dev/go.sum
          go-version-file: ${{ env.GOPATH }}/ansible-dev/go.mod

      - run: go version

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
          workdir: ${{ env.GOPATH }}/ansible-dev
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
